name: 'Design System Adoption'
description: 'Analyze and update your design system adoption in zeroheight'
author: 'zeroheight'
branding:
  icon: 'bar-chart'
  color: 'purple'

runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Analyze and update
      run: npx @zeroheight/adoption-cli analyze --interactive false --repo-name ${{ github.event.repository.name }}
      shell: bash
